global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:8082']

  - job_name: 'view-service'
    static_configs:
      - targets: ['view-service:8083']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8084']
